version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mapacafe-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 412410
      MYSQL_DATABASE: mapacafe
    ports:
      - "3308:3306"
    volumes:
      mysql_data:

  backend:
    build: ./backend
    container_name: mapacafe-api
    restart: always
    ports:
      - "5276:8080"
    depends_on:
      - mysql
    environment:
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=mapacafe;user=root;password=412410"

  frontend:
    build: ./frontend
    container_name: mapacafe-front
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend