// <auto-generated />
using MapaCafe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MapaCafe.Migrations
{
    [DbContext(typeof(MapaCafeContext))]
    [Migration("20250531195724_OOMigrations")]
    partial class OOMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MapaCafe.Models.CadastroCafeteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CadastroUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("avaliacaoCafeteria")
                        .HasColumnType("int");

                    b.Property<string>("bairroCafeteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("bebidaFavorita")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("cepEndereco")
                        .HasColumnType("longtext");

                    b.Property<string>("comidaFavorita")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("complementoEndereco")
                        .HasColumnType("longtext");

                    b.Property<string>("nomeCafeteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("numeroEndereco")
                        .HasColumnType("int");

                    b.Property<string>("observacoesCafeteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ruaCafeteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CadastroUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cafeterias");
                });

            modelBuilder.Entity("MapaCafe.Models.DadosUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("emailUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("telefoneUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DadosUsuario");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DadosUsuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MapaCafe.Models.CadastroUsuario", b =>
                {
                    b.HasBaseType("MapaCafe.Models.DadosUsuario");

                    b.Property<string>("senhaUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("CadastroUsuario");
                });

            modelBuilder.Entity("MapaCafe.Models.PerfilUsuario", b =>
                {
                    b.HasBaseType("MapaCafe.Models.DadosUsuario");

                    b.Property<string>("biografia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("PerfilUsuario");
                });

            modelBuilder.Entity("MapaCafe.Models.CadastroCafeteria", b =>
                {
                    b.HasOne("MapaCafe.Models.CadastroUsuario", "CadastroUsuario")
                        .WithMany()
                        .HasForeignKey("CadastroUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapaCafe.Models.CadastroUsuario", "Usuario")
                        .WithMany("CafeteriasCadastradas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CadastroUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MapaCafe.Models.CadastroUsuario", b =>
                {
                    b.Navigation("CafeteriasCadastradas");
                });
#pragma warning restore 612, 618
        }
    }
}
