// <auto-generated />
using System;
using MapaCafe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MapaCafe.Migrations
{
    [DbContext(typeof(MapaCafeContext))]
    partial class MapaCafeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MapaCafe.Models.CadastroCafeteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("avaliacaoCafeteria")
                        .HasColumnType("int");

                    b.Property<string>("bairroCafeteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("bebidaFavorita")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("cepEndereco")
                        .HasColumnType("longtext");

                    b.Property<string>("comidaFavorita")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("complementoEndereco")
                        .HasColumnType("longtext");

                    b.Property<string>("nomeCafeteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("numeroEndereco")
                        .HasColumnType("int");

                    b.Property<string>("observacoesCafeteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ruaCafeteria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cafeterias");
                });

            modelBuilder.Entity("MapaCafe.Models.DadosUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("emailUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("telefoneUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DadosUsuario");

                    b.HasDiscriminator().HasValue("DadosUsuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MapaCafe.Models.CadastroUsuario", b =>
                {
                    b.HasBaseType("MapaCafe.Models.DadosUsuario");

                    b.Property<string>("senhaUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("CadastroUsuario");
                });

            modelBuilder.Entity("MapaCafe.Models.PerfilUsuario", b =>
                {
                    b.HasBaseType("MapaCafe.Models.DadosUsuario");

                    b.Property<string>("biografia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("PerfilUsuario");
                });

            modelBuilder.Entity("MapaCafe.Models.CadastroCafeteria", b =>
                {
                    b.HasOne("MapaCafe.Models.CadastroUsuario", "Usuario")
                        .WithMany("CafeteriasCadastradas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MapaCafe.Models.CadastroUsuario", b =>
                {
                    b.Navigation("CafeteriasCadastradas");
                });
#pragma warning restore 612, 618
        }
    }
}
